# Generated by Django 5.1 on 2024-08-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='seat_left',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
