# Generated by Django 5.1 on 2024-08-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_slot_seat_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='seat_left',
        ),
        migrations.AddField(
            model_name='museum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='museum_images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
