# Generated by Django 5.1.1 on 2024-09-07 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_slot_seat_left_museum_image_ticket_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='slot',
        ),
        migrations.AddField(
            model_name='ticket',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.museum'),
        ),
    ]
