# Generated by Django 5.1.1 on 2024-09-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ticket_slot_ticket_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='venue',
        ),
        migrations.AddField(
            model_name='ticket',
            name='slot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.slot'),
        ),
    ]
