# Generated by Django 5.1.1 on 2024-09-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ticket_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
